language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 064d8b47dfaffd8ae1374f1e5009cf6a5ce51e7e6c30bf88c4d2ea9190996889
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
